import { Boxes, Check, Grid3X3, Image as ImageIcon, Plus, QrCode, ScanBarcode, Trash2, X } from "lucide-react";
import { referenceAssets } from "../../assets/reference";
import "./operations-preview.css";
import "./reference-layout.css";
import { PackageLabelPreview, OutboundSummary, OutboundActions } from "./PreviewPanels";

type Mode = "label-print" | "label-designer" | "packaging" | "outbound" | "products" | "customers" | "orders" | "reports" | "settings";
const products = ["انگشتر طرح گل", "دستبند طرح قلب", "گردنبند طرح پروانه", "سرویس طرح نگین", "پلاک طرح اسم", "گوشواره طرح حلقه"];

export function OperationsPreviewPage({ mode }: { mode: Mode }) {
  if (mode === "label-designer") return <main className="ops-page"><header className="ops-title"><div><small>محصولات</small><h1>طراح لیبل　⌄</h1></div><b>پیش‌نمایش رابط کاربری</b></header><div className="ops-toolbar">{["جدید","باز کردن","ذخیره","ذخیره نسخه","Undo","Redo","تراز کردن","قفل","گروه","پیش‌نمایش","چاپ تست"].map(x=><button key={x}>{x}</button>)}</div><div className="designer-layout"><aside className="designer-tools"><h3>ابزارها</h3>{[["انتخاب",Grid3X3],["متن",ImageIcon],["QR",QrCode],["تصویر",ImageIcon],["لوگو",Boxes],["خط",X]].map(([name,Icon])=><button key={name as string}><Icon size={19}/>{name as string}</button>)}</aside><section className="designer-canvas"><div className="canvas-ruler">0　 10　 20　 30　 40　 50　 60　 70　 80　 90 mm</div><div className="label-art"><img src={referenceAssets.productRegistrationLabel} alt="پیش‌نمایش لیبل"/><i/></div><div className="zoom-bar">⌕　 219%　 ⊞　 ▦</div></section><aside className="designer-properties"><h3>ویژگی‌های شیء</h3><select><option>QR Code 1</option></select>{["موقعیت و اندازه","ظاهر","داده (QR Code)","سایر"].map(x=><section key={x}><strong>{x}</strong><p>X　54.10 mm　　Y　12.30 mm</p><p>W　22.00 mm　　H　22.00 mm</p></section>)}</aside></div><div className="template-strip"><h3>قالب‌های آماده</h3>{products.map(x=><div className="template-card" key={x}><img src={referenceAssets.productRegistrationLabel} alt=""/><span>{x}</span></div>)}</div></main>;
  if (mode === "packaging") return <Packaging />;
  if (mode !== "outbound") return <UtilityPage mode={mode} />;
  return <Outbound />;
}

function UtilityPage({ mode }: { mode: Exclude<Mode, "label-designer" | "packaging" | "outbound"> }) {
  const titles: Record<typeof mode, string> = { "label-print": "چاپ لیبل", products: "محصولات", customers: "مشتریان", orders: "سفارش‌ها", reports: "گزارش‌ها", settings: "تنظیمات" };
  const title = titles[mode];
  return <main className="ops-page utility-page"><header className="ops-title"><div><small>Gold Label Studio Pro</small><h1>{title}</h1><p>پیش‌نمایش رابط کاربری</p></div><button>راهنما　?</button></header><section className="utility-hero"><h2>{mode === "label-print" ? "آماده چاپ لیبل‌ها" : `مدیریت ${title}`}</h2><p>این بخش مطابق زبان بصری تأییدشده‌ی برنامه طراحی شده و فعلاً بدون عملیات واقعی است.</p><div className="utility-search"><input placeholder={mode === "label-print" ? "جستجوی کد محصول یا بسته..." : `جستجو در ${title}...`} /><button>جستجو</button></div></section><section className="data-panel"><h2>آخرین موارد</h2><table><thead><tr><th>#</th><th>کد</th><th>عنوان</th><th>وضعیت</th><th>تاریخ</th><th>عملیات</th></tr></thead><tbody>{products.map((p,i)=><tr key={p}><td>{i+1}</td><td>GL-250904-00{i+1}</td><td>{p}</td><td className="good">آماده</td><td>۱۴۰۴/۰۶/۱۳</td><td><button className="table-action">مشاهده</button></td></tr>)}</tbody></table></section></main>;
}

function Packaging(){return <main className="ops-page packaging-page"><header className="ops-title"><div><small>عملیات</small><h1>بسته‌بندی</h1><p>اسکن سریع و ایجاد بسته</p></div><button>راهنمای بسته‌بندی　?</button></header><div className="pack-top"><section className="scan-panel"><h2>اسکن محصول (QR Code)</h2><p>برای اسکن، بارکد محصول را مقابل دوربین قرار دهید</p><div className="scan-box"><QrCode size={48}/><b>آماده اسکن</b></div><div className="manual-add"><input placeholder="کد محصول را وارد کنید..."/><button><ScanBarcode/></button><span>یا</span><button><Plus/> افزودن به بسته</button></div></section><aside className="current-package"><h2>اطلاعات بسته جاری</h2><p>کد بسته　 <b>PK-250604-00125</b></p><p>تعداد اقلام　 <b>۱۲ قلم</b></p><p>وزن کل　 <b>443.725 گرم</b></p><p>اپراتور جاری　 <b>ادمین</b></p><strong>در حال بسته‌بندی</strong></aside></div><div className="ops-actions"><button className="green">ایجاد بسته　＋</button><button className="gold">پایان بسته　✓</button><button>چاپ لیبل بسته　🖨</button><button className="danger">حذف آخرین　🗑</button></div><section className="data-panel"><h2>لیست اقلام اسکن شده</h2><table><thead><tr><th>#</th><th>کد</th><th>نام</th><th>وزن</th><th>عیار</th><th>وضعیت</th></tr></thead><tbody>{products.map((p,i)=><tr key={p}><td>{i+1}</td><td>R-250604-00{i+125}</td><td>{p}</td><td>4.385</td><td>750</td><td className="good">افزوده شد ✓</td></tr>)}</tbody></table></section><PackageLabelPreview/></main>}
function Outbound(){return <main className="ops-page outbound-page"><header className="ops-title"><div><small>انبار</small><h1>خروج کالا</h1><p>اسکن و ثبت خروج محصولات از انبار</p></div><button>بازگشت　‹</button></header><div className="metrics">{[["تعداد اسکن شده","128"],["جمع وزن","483.725 g"],["تعداد خطا","7"],["زمان جلسه","00:24:18"]].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div><section className="outbound-scan"><h2>منتظر اسکن...</h2><p>بارکد محصول را اسکن کنید</p><div><ScanBarcode/><input placeholder="بارکد را وارد نمایید"/></div></section><div className="alerts"><article className="success"><Check/><b>اسکن موفق</b><span>انگشتر طرح گل　R-250904-00125　|　4.385 g</span></article><article className="error"><X/><b>بارکد تکراری</b><span>این بارکد قبلاً ثبت شده است</span></article></div><section className="data-panel"><h2>آخرین اسکن‌ها</h2><table><thead><tr><th>ردیف</th><th>زمان</th><th>کد</th><th>نام محصول</th><th>وزن</th><th>وضعیت</th></tr></thead><tbody>{products.slice(0,5).map((p,i)=><tr key={p}><td>{i+1}</td><td>10:2{i}:31</td><td>R-250904-0012{i}</td><td>{p}</td><td>4.385 g</td><td className={i===2?"bad":"good"}>{i===2?"بارکد تکراری":"موفق ✓"}</td></tr>)}</tbody></table></section><OutboundSummary/><OutboundActions/></main>}
